#!/bin/bash
set -eo pipefail

host="$(ifconfig eno1 | grep inet | grep netmask | awk '{print $2}' || echo '127.0.0.1')"

if health="$(curl -fsSL "http://$host:9200/_cat/health?h=status")"; then
	health="$(echo "$health" | sed -r 's/^[[:space:]]+|[[:space:]]+$//g')" # trim whitespace (otherwise we'll have "green ")
	if [ "$health" != 'red' ]; then
		exit 0
	fi
	echo >&2 "unexpected health status: $health"
fi

# If the probe returns 2 ("starting") when the container has already moved out of the "starting" state then it is treated as "unhealthy" instead.
exit 2
